### ISSUE TITLE
probleme with  jquery-1.6.1.js

### ISSUE THREAD

**Issue by salkii** [smohadjer/jquery.slideshow#2]
hello i just create a slide with http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js locally

but when i integrate the slider on my website with  jquery-1.6.1.js is not working?
can any one help me

**Comment by smohadjer** [comment]
Sorry for being late to respond, for some reason I didn't get any email from github when you posted this. Anyways, I tested slideshow.html in demo folder with jquery from your comment and couldn't see any problems. Do you have a link that I can have a look at?
